// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjhiw9wOv3kAKIBj1DmBhX2s6cDfFJyc',
    appId: '1:746475728672:web:d9da2d94ef40b285bcb145',
    messagingSenderId: '746475728672',
    projectId: 'eventconnect-1fc77',
    authDomain: 'eventconnect-1fc77.firebaseapp.com',
    storageBucket: 'eventconnect-1fc77.firebasestorage.app',
    measurementId: 'G-H5M18CFKX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWGIn5qsyT_ZR6wO5ib1MHQL_pQA0I-_k',
    appId: '1:746475728672:android:41a0e923710eba6abcb145',
    messagingSenderId: '746475728672',
    projectId: 'eventconnect-1fc77',
    storageBucket: 'eventconnect-1fc77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSeKcZmpuNA4O3U_0waACtICkO66XMzU8',
    appId: '1:746475728672:ios:af638ece9db5f3d5bcb145',
    messagingSenderId: '746475728672',
    projectId: 'eventconnect-1fc77',
    storageBucket: 'eventconnect-1fc77.firebasestorage.app',
    iosBundleId: 'com.eventconnect.eventConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSeKcZmpuNA4O3U_0waACtICkO66XMzU8',
    appId: '1:746475728672:ios:af638ece9db5f3d5bcb145',
    messagingSenderId: '746475728672',
    projectId: 'eventconnect-1fc77',
    storageBucket: 'eventconnect-1fc77.firebasestorage.app',
    iosBundleId: 'com.eventconnect.eventConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFjhiw9wOv3kAKIBj1DmBhX2s6cDfFJyc',
    appId: '1:746475728672:web:24ba2d2dbe902657bcb145',
    messagingSenderId: '746475728672',
    projectId: 'eventconnect-1fc77',
    authDomain: 'eventconnect-1fc77.firebaseapp.com',
    storageBucket: 'eventconnect-1fc77.firebasestorage.app',
    measurementId: 'G-C8T5R7E1HL',
  );
}
